### ISSUE TITLE
updateDisplay() in every function makes it really inefficient

### ISSUE THREAD

**Issue by BrowserCookie** [StevePaget/Pygame_Functions#12]
My friend and I wrote a game using the library and had significant fps issues when multiple sprites were on the screen at the same time. I looked through the library and discovered that the display was updated after every sprite change. We moved this function call to the tick() function and noticed a significant boost in performance and fps. It makes it far more efficient to update the display upon every clock tick because the tick rate is then mirrored by the frame rate.

**Comment by StevePaget** [comment]
This is true. I considered leaving it out of the functions, and just using
updateDisplay manually when you want to refresh. Because I use it in an
education environment with young kids, I wanted it to be as Scratch-like as
possible. When someone says "showSprite", they expect it to show!

Your solution works well, though. It's something to consider.

**Comment by StevePaget** [comment]
This has now been implemented. Have a look at the new setScreenRefresh and updateDisplay functions in the wiki.
It will now handle hundreds of sprites at once.
