### ISSUE TITLE
setBackgroundImage(img) returns error " 'str' object has no attribute 'blit' "

### ISSUE THREAD

**Issue by thatguythatsincharge** [StevePaget/Pygame_Functions#13]
I set the background to my image name, `setBackgroundImage("stars.png")`, however, I keep getting an error stating  "'str' object has no attribute 'blit'". I checked the code out and it seems to me that it should work fine. 
`def setBackgroundImage(img):
    global bgSurface, backgroundImage
    surf = loadImage(img)
    backgroundImage = surf
    screen.blit(surf, [0, 0])
    bgSurface = screen.copy()
    updateDisplay()`
I just don't know what I am doing wrong. If anyone could help me I would greatly appreciate it.

`#Import librarys
import pygame, math
from pygame_functions import *
pygame.init()

##game setup##
horSize = 1000
vertSize = 750
screen = pygame.display.set_mode((horSize, vertSize))
#screenSize(horSize, vertSize)

rocket = makeSprite("rocket1.png")
pygame.display.set_caption("Rocket Game")

setBackgroundImage(convert.alpha("stars.png"))

showSprite(rocket)`

**Comment by StevePaget** [comment]
This may be because the image can't be found. Can you check the file name and file location first?

**Comment by thatguythatsincharge** [comment]
I did several times and I have the file in the right place and made sure I had the file type correct. eventually, I restructured my whole code however, it still gives me the same error :(
If you or anyone would like to help me out with this my project is here ( https://github.com/thatguythatsincharge/Sprites ) the code is slightly messy...sorry.
I'd really appreciate it.

**Comment by StevePaget** [comment]
OK, the problem is that you are using some native pygame functions instead of the ones embedded with pygame_functions.

The one that's causing the problem is when you create your screen using :

`self.screen = pygame.display.set_mode((WIDTH, HEIGHT)) #display surface the reps the screen`

This makes a window, but pygame_functions doesn't know about it, so when you try to use the pygame_functions command setBackgroundImage, it can't find the screen.

A solution would be to make it so that pygame_functions gave you access to the screen object so that you can manipulate it directly in your own code. If you went into pygame_functions and added `return screen` onto the end of the setScreeenSize() function, then you could change your code to say:

```
    def __init__(self): #stuff that needs to happen on game startup
        # initialize pygame and create window
        pg.init()
        pg.mixer.init()
        self.screen =  screenSize(WIDTH, HEIGHT)
        def caption(caption): # creates a function called "caption()" that takes a string perameter
            pg.display.set_caption(caption)
        caption("Astroides")
        setBackgroundImage("stars.png")
        self.clock = pg.time.Clock()
        self.running = True
```

However, judging from your code, it seems to me that you know quite a bit about pygame (making sprite groups, updating etc), so maybe you don't need pygame_functions? It's mostly designed for people who don't want the hassle of learning about blitting and filling the screen by hand.

**Comment by thatguythatsincharge** [comment]
😅 I don't know anything about pygame but thanks for the compliment. this seems to do the trick but I still need to work out other bugs that I don't want to bother you with. THANK YOU SO MUCH!
