### ISSUE TITLE
AttributeError: 'str' object has no attribute 'blit'

### ISSUE THREAD

**Issue by pramli** [StevePaget/Pygame_Functions#25]
Hi Steve, 
I made a simple quiz project, with multiple given answers to chose from. However, I would like to experiment with text input option, and i found your lesson on youtube (pygame_functions: Text Outputs and Inputs). It works perfectly on it's own, but i have problem implementing it in my own code. I'm a novice and I teach myself using online resources, so my code is probably "ugly", but it works :) 
I went through some previous question on this topic, and I think the problem is in gameDisplay.fill line, but I'm not sure how to fix it.

Here is the shortened code:

def question_1():
    q1 = True
    while q1:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                quit()

        gameDisplay.fill(white)

        question_message("question number 1: ", blue, -160, size="med")
        question_message("what color is the sky?", blue, -20, size="med")

        wordbox = makeTextBox(10, 80, 300, 0, "enter your answer", 10, 40)
        showTextBox(wordbox)
        entry = textBoxInput(wordbox)

        score(points)
        pygame.display.update()

and the error is:
  File "test.py", line 157, in question_1
    showTextBox(wordbox)
  File "pygame_functions.py", line 663, in showTextBox
    updateDisplay()
  File "pygame_functions.py", line 674, in updateDisplay
    spriteRects = spriteGroup.draw(screen)
  File "PycharmProjects\pop_quiz\venv\lib\site-packages\pygame\sprite.py", line 568, in draw
    surface_blit = surface.blit
AttributeError: 'str' object has no attribute 'blit'

 
Thank you so much for your lessons on youtube!

**Comment by pramli** [comment]
Thanks for the quick reply.
gameDisplay is a Surface Object which in set mode is setting a width and a height. Then, when gameDisplay.fill is called it is setting(filling) the Surface with a specific color.
My code is in the repository below and I suspect the error is showing up between lines 140 and 142, where i have put parts of your code. If I comment these lines out, it works without a problem. 
https://github.com/pramli/quiz_pygame

**Comment by StevePaget** [comment]
Thanks for that. The problem is that you are using pygame in its raw form for most of your display functions, but only using pygame_functions for the text box. When you import pygame_functions, it does a lot of the work that you are doing yourself (initialising the mixer etc) and it expects that you'll be creating a display surface using screenSize()
Then, when you use it to create a TextBox, pygame_functions assigns this to a sprite group that exists behind the scenes, and tries to blit it onto its _own_ display surface, not the one you have made.

So, essentially, it looks like you're probably at a level of pygame knowledge that means you don't need the helpful shortcut of pygame_functions to make a display and draw stuff to it, implement sound etc. I'm guessing you just wanted help implementing a textbox, in which case you might be able to pick out the relevant pieces from pygame_functions and re-integrate them into your own program. I suggest copying the newTextBox class into your program, which contains the code for grabbing the keyboard and which creates a sprite Surface, and blitting it to your display manually when you update your display.

**Comment by StevePaget** [comment]
I've had a little play with your code. If you make the following changes, you can switch to using the pygame_functions display without too much messing around:


`
#Get rid of the extra import
from pygame_functions import *

#get rid of the mixer initialising

black = (0,0,0)
white = (255, 255, 255)
red = (255, 0, 0)
light_red = (255, 102, 102)
green = (0, 200, 0)
light_green = (144, 238, 144)
blue = (0, 100, 250)
light_blue = (100, 200, 255)
yellow = (255, 255, 0)
light_yellow =(255, 250, 205)

display_width = 1200
display_height = 700

button_width = 100
button_height = 50

#use screenSize to grab the correct display surface
gameDisplay = screenSize(display_width, display_height)
pygame.display.set_caption("pop quiz")
icon = pygame.image.load("pq.bmp")
pygame.display.set_icon(icon)

#these functions can be used to control sounds
correct_answer_sound = makeSound("my_man.wav")
wrong_answer_sound = makeSound("nope.wav")
makeMusic("1.mp3")
playMusic()

#the rest of it should now work...
`

I've made these changes, and now I get the input TextBox appearing with the first question.

Hopefully that's enough to get you going!

**Comment by pramli** [comment]
Steve,

It's exactly what I needed, thank you so much for your time and effort.

**Comment by StevePaget** [comment]
No problem!

**Comment by pramli** [comment]
Steve, 

It's a different issue, but i have problem changing the font and color of the text in textbox. 
I tried changing it in newTextBox class, but nothing would happen:
  self.fontFace = pygame.font.match_font("Arial")
        self.fontColour = pygame.Color("black")
it still stays Arial black, no matter what i put in brackets. I tried changing .match_font() with .Sysfont() and .Font(), and i would add .ttf at the end of the font name, but with no effect. 
Any suggestions?
