### ISSUE TITLE
Closing window with 'X'

### ISSUE THREAD

**Issue by comport9** [StevePaget/Pygame_Functions#34]
Sorry, new to Github. Couldn't find an appropriate way to communicate this. Just wanted to your thoughts on the code I added to my copy of pygame_functions.py

Added this to endWait() in the while loop, but after the if statement. Had to add sys.exit() otherwise it generated an error. 
Is this the appropriate way to implement this?

`for event in pygame.event.get():
			if event.type == pygame.QUIT:
				pygame.quit()
				sys.exit()`

Anyways, just wanted to add my 2 cents. Again, sorry for posting here.

**Comment by zerokrezan** [comment]
Yeah, it’s actually what you did. I would suggest you to use pygame.quit() as you did and then after pygame.quit() don’t use sys.exit() but exit(). But it has the same impact. So yes, you did right. If you have questions you can always text to me. Don’t worry about that, I like to mess about with programming especially python.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: comport9 <notifications@github.com>
Gesendet: Tuesday, March 3, 2020 7:23:59 PM
An: StevePaget/Pygame_Functions <Pygame_Functions@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [StevePaget/Pygame_Functions] Closing window with 'X' (#34)


Sorry, new to Github. Couldn't find an appropriate way to communicate this. Just wanted to your thoughts on the code I added to my copy of pygame_functions.py

Added this to endWait() in the while loop, but after the if statement. Had to add sys.exit() otherwise it generated an error.
Is this the appropriate way to implement this?

for event in pygame.event.get(): if event.type == pygame.QUIT: pygame.quit() sys.exit()

Anyways, just wanted to add my 2 cents. Again, sorry for posting here.

**Comment by zerokrezan** [comment]
If you are interested we can program together. So we both can learn more about python.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Rezan Hüseyin Yilmaz <zerokrezan@hotmail.de>
Gesendet: Wednesday, March 4, 2020 6:55:50 AM
An: StevePaget/Pygame_Functions <reply@reply.github.com>; StevePaget/Pygame_Functions <Pygame_Functions@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [StevePaget/Pygame_Functions] Closing window with 'X' (#34)

Yeah, it’s actually what you did. I would suggest you to use pygame.quit() as you did and then after pygame.quit() don’t use sys.exit() but exit(). But it has the same impact. So yes, you did right. If you have questions you can always text to me. Don’t worry about that, I like to mess about with programming especially python.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: comport9 <notifications@github.com>
Gesendet: Tuesday, March 3, 2020 7:23:59 PM
An: StevePaget/Pygame_Functions <Pygame_Functions@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [StevePaget/Pygame_Functions] Closing window with 'X' (#34)


Sorry, new to Github. Couldn't find an appropriate way to communicate this. Just wanted to your thoughts on the code I added to my copy of pygame_functions.py

Added this to endWait() in the while loop, but after the if statement. Had to add sys.exit() otherwise it generated an error.
Is this the appropriate way to implement this?

for event in pygame.event.get(): if event.type == pygame.QUIT: pygame.quit() sys.exit()

Anyways, just wanted to add my 2 cents. Again, sorry for posting here.

**Comment by comport9** [comment]
Thanks! I'd love to do that. I've been trying on and off for a while, never got very far. Real life and all. What forum can we use? (Github doesn't have messaging I guess...)

**Comment by zerokrezan** [comment]
Skype would be the best.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: comport9 <notifications@github.com>
Gesendet: Wednesday, March 4, 2020 7:39:44 AM
An: StevePaget/Pygame_Functions <Pygame_Functions@noreply.github.com>
Cc: zerokrezan <zerokrezan@hotmail.de>; Comment <comment@noreply.github.com>
Betreff: Re: [StevePaget/Pygame_Functions] Closing window with 'X' (#34)


Thanks! I'd love to do that. I've been trying on and off for a while, never got very far. Real life and all. What forum can we use? (Github doesn't have messaging I guess...)

**Comment by zerokrezan** [comment]
That’s my skype account. Just send me a short message. See you there

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Rezan Hüseyin Yilmaz <zerokrezan@hotmail.de>
Gesendet: Wednesday, March 4, 2020 2:27:28 PM
An: StevePaget/Pygame_Functions <reply@reply.github.com>; StevePaget/Pygame_Functions <Pygame_Functions@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Betreff: Re: [StevePaget/Pygame_Functions] Closing window with 'X' (#34)

Skype would be the best.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: comport9 <notifications@github.com>
Gesendet: Wednesday, March 4, 2020 7:39:44 AM
An: StevePaget/Pygame_Functions <Pygame_Functions@noreply.github.com>
Cc: zerokrezan <zerokrezan@hotmail.de>; Comment <comment@noreply.github.com>
Betreff: Re: [StevePaget/Pygame_Functions] Closing window with 'X' (#34)


Thanks! I'd love to do that. I've been trying on and off for a while, never got very far. Real life and all. What forum can we use? (Github doesn't have messaging I guess...)

**Comment by StevePaget** [comment]
This has now been added to endWait() and tick()
