### ISSUE TITLE
Graphics Window Issues

### ISSUE THREAD

**Issue by ThisGrooveGotMe** [StevePaget/Pygame_Functions#40]
My program has no errors. However, the code I wrote doesn't project in the Graphics Window meaning there's only grey screen. (I am on a MacBook Air 2017). TY for any help.

**Comment by StevePaget** [comment]
If you post your program, I can take a look.

**Comment by ThisGrooveGotMe** [comment]
![Screenshot 2020-05-24 at 16 51 34](https://user-images.githubusercontent.com/64593427/82757143-dd572d80-9dde-11ea-814d-118d06517f63.png)


I'm using 'Atom'. And Here's what I get:

![Screenshot 2020-05-24 at 16 53 32](https://user-images.githubusercontent.com/64593427/82757201-1e4f4200-9ddf-11ea-86e8-f2b52d77d8e3.png)

**Comment by StevePaget** [comment]
Weird. I can't replicate that. Might be a Mac thing.

**Comment by CoolCat467** [comment]
from pygame_functions import *

screenSize(1200, 630)
setBackgroundColour('red')

start_game = makeLable("Welcome to Escape! The craziest Escape Room Simulations on Earth.", 40, 10, 10 'red', 'Comic Sans MS', 'yellow')
showLable(start_game)

#more stuffs, not relevant to issue experienced

**Comment by CoolCat467** [comment]
Interesting thing, the function setBackgroundColour does not declare background as a global. Maybe wierd things on mac os involving the context manager?
And why does the background.setColour just copy the screen surface? Why not just set it to a new surface of the size of the screen filled with the given colour argument instead of filling the screen with the background color, **Causing a screen update**, and copying it? That would mean if you have rapidly changing background colors, or really any background colour change, for about one frame the entire screen is forced to be that color, and with lower end computers with less screen updates that could be a very distracting problem.
In newLabel's init function, there is no check for a valid font. It just throws it into pygame.font.Font, and could potentially cause problems with an invalid font name.
Why are lines split by HTML break statements ('<br>') in newLabel.renderText? Why not just the newline character, '\n'? Is this secretly built for a web browser?
In parseColour, there is no check for if a color input is actually valid. It just checks to see if it's a string or not, and if pygame.Color were to throw an error because of invalid color names, there is nothing to catch it.
Finally, I know I could just be being paranoid, but the showLabel function does not declare textboxGroup as a global.

**Comment by CoolCat467** [comment]
Final thing that might help fix:
Ensure screenRefresh is set to True, or having it be false and manually calling pygame.display.refresh() in your main event loop.

**Comment by StevePaget** [comment]
Yeah, the problem is probably the endWait() which appears before the label
is made. EndWait() waits for an Esc and then ends the program.
