### ISSUE TITLE
Text Error

### ISSUE THREAD

**Issue by LucaChkt** [StevePaget/Pygame_Functions#8]
`from pygame_functions import*
import pygame
from pygame.locals import*

pygame.init()
screen=pygame.display.set_mode ((1200,675),RESIZABLE)

#infiniteloop
def game_intro ():
    pygame.init()
    
    intro= True
    while intro:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                quit()

        menu= pygame.image.load("menu.JPG").convert()
        screen.blit(menu, (0,0))
        wordBox = makeTextBox(10,80,300, "Enter text here", 0, 24)
        showTextBox(wordBox)
        entry = textBoxInput(wordbox)
        pygame.display.flip()
        pygame.time.delay(2000)

game_intro()

intro()
`

**Comment by StevePaget** [comment]
The error you mentioned on the Youtube video ("TypeError: text must be a unicode or bytes") is because you have left out the fourth parameter in the makeTextbox command (You need a case parameter before the default text)

There are some other errors though, such as mis-spelling wordBox and the fact that you're only half-using pygame_functions and making up the rest using pygame raw. If you don't set up the screen using the screenSize function, for example, it will cause errors when you try to use showTextBox.

While you can dip into pygame to make things more efficient, some things in pygame_functions are designed to work together.

**Comment by LucaChkt** [comment]
Ok thanks you, i'm novice french  student, so i may have not understand
correctly your video, i apologize
